### ISSUE TITLE
Submit link request to Fit Commit

### ISSUE THREAD

**Issue by m1foley** [DanielaValero/fit-commit-js#13]
This is a cool project! When you feel it's ready for public release, submit an issue to [Fit Commit](https://github.com/m1foley/fit-commit) and I'll link to it in the README.

**Comment by DanielaValero** [comment]
Hi, just read your message. Sure :) I am doing it as a pet project, but the first release should be ready soon. Was busy with lots of other stuff.

greetings

**Comment by DanielaValero** [comment]
Hi Mike,

Sent the link in this issue: https://github.com/m1foley/fit-commit/issues/29
