### ISSUE TITLE
Use with husky

### ISSUE THREAD

**Issue by burt202** [DanielaValero/fit-commit-js#33]
Hi, great port of fit-commit! How would you use this with something like [husky](https://github.com/typicode/husky), where the hooks are written as npm run tasks? I would like to hear your thoughts? Many thanks

**Comment by DanielaValero** [comment]
Hello, I had the notification settings off and did not get it for your message.

Let me have a look at husky, once I get right how it works in the background, I'd be able to provide some ideas.

Greetings!

**Comment by okonet** [comment]
Same question with https://github.com/observing/pre-commit

**Comment by DanielaValero** [comment]
Well, we don't necessarily would need to removing the install/uninstall. Only if you run them, the sym link will be created.

But for sure, being able to have the commit validation run with tools like husky or pre-commit would definitely ensure that the commit is really validated, as most of the people don't create the sym link

@okonet what do you mean with exporting the executable in the package.json ? Not sure I get what you mean

**Comment by okonet** [comment]
AFAIK you can export multiple binaries in `package.json` using `bin` key: https://docs.npmjs.com/files/package.json#bin

So you could just export the "hook" version here: https://github.com/DanielaValero/fit-commit-js/blob/master/package.json#L9

**Comment by DanielaValero** [comment]
@okonet nice tip!!!

**Comment by burt202** [comment]
Closing. My solution

```
  "husky": {
    "hooks": {
      "commit-msg": "node ./node_modules/fit-commit-js/lib/hook.js .git/COMMIT_EDITMSG",
    }
  },
```
